# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f4024604e16d989ff947d394339416db38618e41d0ac42f5fffa198dc0d5baeafd7b61a53815063c0eedfb5e5e66f19d9b54ec26cdd9fb78f75f41e75f4b304

test:
  secret_key_base: 8b9dc15f8435e653d7f076ea91f90d7a98ae352499727d7f35b0d1e34d92dbb5881f644cde129de2fdc1f122ffb62f64e3bc3674dcc2015133701ccc2e8b5647

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
